name: Spring Boot CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: EC2 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            /home/ubuntu/temp.sh
